/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <string.h>
#include "base64.h"
#include "hmac.h"

#include "com_jia13_encrypt_SignatureEncryptor.h"

//内置secureKey,更安全
static char *secureKey = "test";

JNIEXPORT jstring JNICALL Java_com_jia13_encrypt_SignatureEncryptor_encrypt(
		JNIEnv *env, jobject obj, jstring paramString, jstring keyString) {

	char * ch[2];
	unsigned char buffer[64] = { 0 };
	unsigned char result[64] = { 0 };
	jstring s = NULL;
	ch[0] = (char*) ((*env)->GetStringUTFChars(env, paramString, 0));
	ch[1] = (char*) ((*env)->GetStringUTFChars(env, keyString, 0));

	char *paramBuffer = (char *) malloc(strlen(ch[0]) + strlen(ch[1]) + strlen(ch[1]) + 1);

	strcpy(paramBuffer,ch[1]);
	strcat(paramBuffer,ch[0]);
	strcat(paramBuffer,ch[1]);
	hmac_sha1(ch[1], strlen(ch[1]), paramBuffer, strlen(paramBuffer), buffer);
	
	base64_encode(buffer, strlen(buffer),result);
	s = (*env)->NewStringUTF(env, result);
	free(paramBuffer);
	return s;
}

JNIEXPORT jstring JNICALL Java_com_jia13_encrypt_SignatureEncryptor_encryptWithoutSecurekey
(JNIEnv *env, jobject obj, jstring paramString)
{

	char * ch[2];
	unsigned char buffer[64] = { 0 };
	unsigned char result[64] = { 0 };
	jstring s = NULL;
	ch[0] = (char*) ((*env)->GetStringUTFChars(env, paramString, 0));
	ch[1] = secureKey;
	char *paramBuffer = (char *) malloc(strlen(ch[0]) + strlen(ch[1]) + strlen(ch[1]) + 1);

	strcpy(paramBuffer,ch[1]);
	strcat(paramBuffer,ch[0]);
	strcat(paramBuffer,ch[1]);
	hmac_sha1(ch[1], strlen(ch[1]), paramBuffer, strlen(paramBuffer), buffer);
	
	base64_encode(buffer, strlen(buffer),result);
	s = (*env)->NewStringUTF(env, result);
	free(paramBuffer);
	return s;

}
